services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: control-stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
